### ISSUE TITLE
大佬，我编译运行了为什么没有输出啊

### ISSUE THREAD

**Issue by mokurin000** [nyaaaww/unmpkg#1]

**Comment by nyaaaww** [comment]
> _未提供描述。_

Because I have not yet completed,the part for creating folders is temporarily unavailable.

**Comment by aqnya** [comment]
> _No description provided._

因为我还没写完，虽然这个项目其实我早在前几个月就已经完工，并且程序在我的酷安有发布，但是源码因为刷机的原因丢失了，这一份是重写的，关于创建目录的部分有一些问题，我在忙其它项目，暂时没有精力继续完成，你可以在这个链接里拿到我之前的程序
[https://yun.139.com/sharewap/#/m/i?1J5C3LyQJtdic](url)

**Comment by aqnya** [comment]
对了，这一份程序是为arm64的Android编译的。
